name: Laravel Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  laravel-test-withdb:
    runs-on: ubuntu-latest

  services:
    mysql-service:
      image: mysql:5.7
      env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: db_test
          ## map the "external" 33306 port with the "internal" 3306
          ports:
            - 33306:3306
          # Set health checks to wait until mysql database has started (it takes some seconds to start)
          options: >-
            --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3



-----IN PROGRESS----