name: "Deployment automation"

on:
  push:
    branches: ["main"]
    
jobs:
  app-deployment:
    name: "Running app"
    runs-on: ubuntu-latest
    
    steps: 
      - name: "Check out code"
        uses: actions/checkout@v2.3.2
        
        
  dependencies-installation:
    name: "Dependency installation"
    needs: app-deployment
    runs-on: ubuntu-latest
    
    steps: 
      - name: "Preparing app..."
        uses: actions/checkout@v2.3.2
        
      - name: "Installing dependencies..."
        run: |
          composer update && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    
  app-deploy:
    name: "Deploy to staging"
    needs: dependencies-installation
    runs-on: ubuntu-latest
    
    steps:
      - name: "Synching files to staging..."
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "ftp.macrohonwater.ph"
          username: "user@stg-mws.macrohonwater.ph"
          password: "#N%sA=s=8MT&"
          server-dir: "/"
          port: 21
          exclude: |
            **/node_modules/**
            **/.DS_Store
            **/.editorconfig
            **/.env.example
            **/.gitattributes
            **/.styleci.yml
            **/.ftpquota
            **/.gitignore
            **/app.zip
            **/deployment-config.json
            **/.git*
            **/.git*/**
            **/.github/**
            **/intprogress.github/**
            **/.htaccess
            **/main.yaml
    
  
    
