name: "Deployment"

on:
  push:
    branches: ["main"]
    
jobs:
  app-deployment:
    name: "Deploy app"
    runs-on: ubuntu-latest
    
    steps: 
      - name: "Check out code"
        uses: actions/checkout@v2.3.2
          
      - name: "Install dependencies"
        run: |
          composer update && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: "Sync files"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "ftp.macrohonwater.ph"
          username: "user@stg-mws.macrohonwater.ph"
          password: "#N%sA=s=8MT&"
          server-dir: "/"
          port: 21
          exclude: |
            **/node_modules/**
            **/.DS_Store
            **/.editorconfig
            **/.env.example
            **/.gitattributes
            **/.styleci.yml
            **/.ftpquota
            **/.gitignore
            **/app.zip
            **/deployment-config.json
            **/.git*
            **/.git*/**
            **/.github/**
            **/intprogress.github/**
            **/.htaccess
            **/main.yaml
    
  
    
